version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - DATABASE_PROXY_URL=${DATABASE_PROXY_URL}
    command: bun start
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PROXY_URL=${DATABASE_PROXY_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped
    volumes:
      - ./prisma-data:/app/prisma
volumes:
  prisma-data:
