version: "3.8"
services:
  app:
    image: app:latest
    ports:
      - 8080:8080
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - DATABASE_PROXY_URL=${DATABASE_PROXY_URL}
        - VITE_WEBSITE_BASE_URL=${VITE_WEBSITE_BASE_URL}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_DISCORD_CLIENT_ID=${VITE_DISCORD_CLIENT_ID}
    command: bun start
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PROXY_URL=${DATABASE_PROXY_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_API_ENDPOINT=${DISCORD_API_ENDPOINT}
      - WEBSITE_BASE_URL=${WEBSITE_BASE_URL}
      - IMGUR_CLIENT_ID=${IMGUR_CLIENT_ID}
      - API_BASE_URL=${API_BASE_URL}
      - VITE_WEBSITE_BASE_URL=${VITE_WEBSITE_BASE_URL}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_DISCORD_CLIENT_ID=${VITE_DISCORD_CLIENT_ID}
      - NOVELAI_TOKEN=${NOVELAI_TOKEN}
    restart: unless-stopped
    volumes:
      - ./prisma-data:/app/prisma
      - ./cache:/app/cache
volumes:
  prisma-data:
  cache:
