name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build using docker-compose
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_PROXY_URL: ${{ secrets.DATABASE_PROXY_URL }}

        run: docker-compose build app

      - name: Tag Docker image
        run: docker tag app ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and pull latest image on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export GHCR_PAT=${{ secrets.GHCR_PAT }}
            echo $GHCR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop app || true
            docker rm app || true
            docker run \
              --name app \
              -p 8080:8080 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e DATABASE_PROXY_URL=${{ secrets.DATABASE_PROXY_URL }} \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              --restart unless-stopped \
              -v $HOME/prisma-data:/app/prisma \
              ghcr.io/${{ github.repository }}:latest
